In [11]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np

data2 = pd.read_csv("https://github.com/andvise/DataAnalyticsDatasets/blob/main/dm_assignment2/sat_dataset_test.csv?raw=True")
data2.head()


c   v  clauses_vars_ratio  vars_clauses_ratio  vcg_var_mean  \
0  1571  69           22.768116            0.043921      0.033331   
1   112   8           14.000000            0.071429      0.625000   
2   369  26           14.192308            0.070461      0.094642   
3   207  21            9.857143            0.101449      0.122843   
4   947  42           22.547619            0.044351      0.074923   

   vcg_var_coeff  vcg_var_min  vcg_var_max  vcg_var_entropy  vcg_clause_mean  \
0       0.240296     0.012731     0.055379         3.565779         0.033331   
1       0.000000     0.625000     0.625000         0.000000         0.625000   
2       0.195329     0.051491     0.121951         2.704781         0.094642   
3       0.117396     0.086957     0.140097         1.935169         0.122843   
4       0.049012     0.060190     0.079197         2.244693         0.074923   

   ...   rwh_0_max    rwh_1_mean  rwh_1_coeff      rwh_1_min     rwh_1_max  \
0  ...   7031250.0   3929.130299          1.0  8.769565e-195   7858.260597   
1  ...    109375.0      0.006519          0.0   6.519258e-03      0.006519   
2  ...   5547500.0  14193.201401          1.0   3.397587e-59  28386.402802   
3  ...   5468750.0  16576.393380          1.0   2.740684e-44  33152.786760   
4  ...  14531250.0   8167.202844          1.0   1.747394e-71  16334.405689   

     rwh_2_mean  rwh_2_coeff  rwh_2_min     rwh_2_max  target  
0   3760.258025          1.0   0.000000   7520.516050       1  
1      0.000198          0.0   0.000198      0.000198       1  
2  13985.119012          1.0   0.000000  27970.238024       0  
3  15957.397700          1.0   0.000000  31914.795400       1  
4   8440.214626          1.0   0.000000  16880.429251       0  

[5 rows x 328 columns]

In [12]:
data2 = data2.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)


In [13]:
data2.fillna(-99999, inplace=True)

In [14]:
target = data2.target
features = data2.drop('target',axis='columns')

In [15]:
features = (features - features.min()) / (features.max() - features.min())
target = (target - target.min()) / (target.max() - target.min())

In [16]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.4)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (289, 327)
X_test shape: (194, 327)
y_train shape: (289,)
y_test shape: (194,)


In [17]:
X_train = X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
y_train = y_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
X_test = X_test.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
y_test = y_test.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)

In [18]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.fit(X_train, y_train).predict(X_test)
y_pred

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1.])

In [19]:
model.score(X_test, y_test)

0.8711340206185567

In [20]:
y_test[:10]

0    0.0
1    0.0
2    1.0
3    0.0
4    1.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
Name: target, dtype: float64

In [21]:
model.predict(X_test[:10])

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
model.predict_proba(X_test[:10])

In [1]:
!git clone https://github.com/Christopher-MJ/CS6405Second_Assignment

Cloning into 'CS6405Second_Assignment'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.


In [2]:
%cd CS6405Second_Assignment

/content/CS6405Second_Assignment


In [3]:
!git init

Reinitialized existing Git repository in /content/CS6405Second_Assignment/.git/


In [4]:
!git config --global user.email "Christopher.m.james001@gmail.com"
!git config --global user.name "Christopher-MJ"

In [5]:
import pickle

In [22]:
pickle.dump(model,  open( "model.pkl", "wb" ))

In [23]:
clss = pickle.load(open("model.pkl", "rb"))

In [24]:
clss

GaussianNB()

In [26]:
clss.predict(X_test)

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1.])

In [ ]:
from io import BytesIO
import pickle
import requests
mLink = 'https://github.com/andreareds/Lab01/blob/main/model2.pkl?raw=true'
mfile = BytesIO(requests.get(mLink).content)
model = pickle.load(mfile)